// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.4.0'
        // navigation-fragment-ktx / navigation-ui-ktxを2.9.8に固定しているため
        // noinspection GradleDependency
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.9.8"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}